In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("df_analysis.csv")
df.head(10)

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,...,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules,license,missing_location
0,1001254,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,2021-10-19,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,Not Provided,False
1,1002102,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,Not Provided,False
2,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",Not Provided,False
3,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,3.0,74.0,2019-06-22,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",Not Provided,False
4,1005754,Large Furnished Room Near B'way,79384379533,Verified,Evelyn,Manhattan,Hell'S Kitchen,40.76489,-73.98493,United States,...,2.0,430.0,2019-06-24,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,Not Provided,False
5,1006307,Cozy Clean Guest Room - Family Apt,75527839483,Unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,2.0,118.0,2017-07-21,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,Not Provided,False
6,1007411,Beautiful 1br on Upper West Side,18824631834,Verified,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,...,5.0,53.0,2019-06-22,0.43,4.0,1.0,163.0,"My ideal guests would be warm, friendly, and r...",Not Provided,False
7,1007964,Central Manhattan/near Broadway,88136055909,Verified,Unknown,Manhattan,Hell'S Kitchen,40.76076,-73.98867,United States,...,2.0,188.0,2019-06-23,1.50,4.0,1.0,258.0,- One of the bedroom closets is not accessible...,Not Provided,False
8,1008516,"Lovely Room 1, Garden, Best Area, Legal rental",26802410424,Verified,Darcy,Brooklyn,South Slope,40.66829,-73.98779,United States,...,4.0,167.0,2019-06-24,1.34,4.0,3.0,47.0,No rules provided,Not Provided,False
9,1009621,West Village Nest - Superhost,46551725984,Verified,Daniel,Manhattan,West Village,40.73530,-74.00525,United States,...,90.0,27.0,2018-10-31,0.22,3.0,1.0,100.0,Arrival time can be no later than 9:00PM unles...,Not Provided,False

In [3]:
df.describe()

,id,host_id,lat,long,construction_year,price,service_fee,minimum_nights,number_of_reviews,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
count,5.237100e+04,5.237100e+04,52367.000000,52367.000000,52371.000000,52371.000000,52371.000000,52371.000000,52371.000000,52371.000000,52371.000000,52371.000000,52371.000000
mean,2.944951e+07,4.917346e+10,40.727481,-73.949088,2012.475759,625.865364,125.124726,7.365336,33.812797,1.382482,3.268756,7.289855,141.977908
std,1.630100e+07,2.852359e+10,0.055638,0.049567,5.754506,331.616811,66.285917,21.388320,53.143543,1.591801,1.281485,30.808005,134.298113
min,1.001254e+06,1.332647e+08,40.504560,-74.249840,2003.000000,50.000000,10.000000,-200.000000,0.000000,0.000000,1.000000,1.000000,-10.000000
25%,1.517805e+07,2.447753e+10,40.687850,-73.982235,2007.000000,340.000000,68.000000,2.000000,3.000000,0.230000,2.000000,1.000000,7.000000
50%,3.027103e+07,4.906904e+10,40.721220,-73.954100,2012.000000,625.000000,125.000000,3.000000,12.000000,0.780000,3.000000,1.000000,100.000000
75%,4.339506e+07,7.384487e+10,40.762510,-73.931850,2017.000000,913.000000,183.000000,5.000000,41.000000,2.090000,4.000000,2.000000,267.000000
max,5.736742e+07,9.876266e+10,40.916970,-73.705220,2022.000000,1200.000000,240.000000,2645.000000,1024.000000,57.310000,5.000000,332.000000,3677.000000

In [4]:
df= df.drop(['id','host_id','house_rules'],axis=1)

In [5]:
df.columns.tolist()

['name',
 'host_identity_verified',
 'host_name',
 'neighbourhood_group',
 'neighbourhood',
 'lat',
 'long',
 'country',
 'country_code',
 'instant_bookable',
 'cancellation_policy',
 'room_type',
 'construction_year',
 'price',
 'service_fee',
 'minimum_nights',
 'number_of_reviews',
 'last_review',
 'reviews_per_month',
 'review_rate_number',
 'calculated_host_listings_count',
 'availability_365',
 'license',
 'missing_location']

In [6]:
print(f"Number of rows detected: {len(df)}")

Number of rows detected: 52371

In [7]:
print("OUTLIER DETECTION AND REMOVAL")
print("-"*30)
print("\nBefore Cleaning: ")

# FINDING PROBLEMATIC VALUES
print(f" -> minimum_nights < 0 : {(df['minimum_nights'] <0 ).sum()}")
print(f" -> minimum_nights > 365 : {(df['minimum_nights'] > 365).sum()}")
print(f" -> availability_365 < 0 : {(df['availability_365'] <0).sum()}")
print(f" -> availability_365 > 365 : {(df['availability_365'] > 365).sum()}")
print(f" -> price = 0 : {(df['price']==0).sum()}")

OUTLIER DETECTION AND REMOVAL
------------------------------

Before Cleaning:
 -> minimum_nights < 0 : 6
 -> minimum_nights > 365 : 14
 -> availability_365 < 0 : 226
 -> availability_365 > 365 : 1400
 -> price = 0 : 0

**1. REMOVE IMPOSSIBLE LOWER VALUES**

In [8]:
df = df[df['minimum_nights'] >= 0]
df = df[df['availability_365'] >= 0]
df = df[df['price'] > 0]
df = df[df['service_fee'] >= 0]

print("\nRemoved negetive values")
print(f"Rows remaining : {len(df)}")

Removed negetive values
Rows remaining : 52139

**2. REMOVE UNREALISTIC UPPER BOUNDS**

In [9]:
df = df[df['minimum_nights'] <= 365]
print(f"Rows remaining: {len(df)}")

Rows remaining: 52125

In [10]:
df=df[df['reviews_per_month'] <= 30]
print(f"Rows removed: {len(df)}")

Rows removed: 52122

**3. REMOVE STATISTICAL OUTLIERS (price)**

In [11]:
Q1_price = df['price'].quantile(0.25)
Q3_price = df['price'].quantile(0.75)
IQR_price = Q3_price - Q1_price

lower_bound = Q1_price - 1.5 * IQR_price
upper_bound = Q3_price + 1.5 * IQR_price

print(f"PRICE IQR ANALYSIS")
print(f" Q1 (25th percentile): ${Q1_price:.2f}")
print(f" Q3 (75th percentile): ${Q3_price:.2f}")
print(f" IQR: ${IQR_price:.2f}")
print(f" valid range: ${lower_bound:.2f} to ${upper_bound:.2f}")

# COUNT OUTLIERS BEFORE REMOVAL
price_outliers = ((df['price'] < lower_bound) | (df['price'] > upper_bound)).sum()
print(f" PRICE OUTLIERS COUNT: {price_outliers}")

PRICE IQR ANALYSIS
 Q1 (25th percentile): $340.00
 Q3 (75th percentile): $913.00
 IQR: $573.00
 valid range: $-519.50 to $1772.50
 PRICE OUTLIERS COUNT: 0

In [12]:
# remove price outliers
df= df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]
print(f"Rows remaining: {len(df)}")

Rows remaining: 52122

**4. REMOVE SERVICE FEE OUTLIERS(IQR METHOD)**

In [13]:
Q1_fee = df['service_fee'].quantile(0.25)
Q3_fee = df['service_fee'].quantile(0.75)
IQR_fee = Q3_fee - Q1_fee

lower_bound = Q1_fee - 1.5 * IQR_fee
upper_bound = Q3_fee + 1.5 * IQR_fee

print(f"PRICE IQR ANALYSIS")
print(f" Q1 (25th percentile): ${Q1_fee:.2f}")
print(f" Q3 (75th percentile): ${Q3_fee:.2f}")
print(f" IQR: ${IQR_fee:.2f}")
print(f" valid range: ${lower_bound:.2f} to ${upper_bound:.2f}")

# COUNT OUTLIERS BEFORE REMOVAL
price_outliers = ((df['service_fee'] < lower_bound) | (df['service_fee'] > upper_bound)).sum()
print(f" PRICE OUTLIERS COUNT: {price_outliers}")

# remove price outliers
df= df[(df['service_fee'] >= lower_bound) & (df['service_fee'] <= upper_bound)]
print(f"Rows remaining: {len(df)}")

PRICE IQR ANALYSIS
 Q1 (25th percentile): $68.00
 Q3 (75th percentile): $183.00
 IQR: $115.00
 valid range: $-104.50 to $355.50
 PRICE OUTLIERS COUNT: 0
Rows remaining: 52122

**5. DATA RANGE VALIDATION**

In [14]:
df['last_review'] = pd. to_datetime(df['last_review'], errors='coerce')
today = pd.Timestamp.today()
airbnb_founded = pd.Timestamp('2008-01-01')
print(f"Valid data range: {airbnb_founded.date()} to {today.date()}")

# count date issues
future_dates = (df['last_review'] > today).sum()
old_dates= (df['last_review']< airbnb_founded).sum()
print('-'*50)
print(f"Future dates found: {future_dates}")
print(f"Dates before 2008: {old_dates}")
print("-"*50)
df=df[(df['last_review'] >= airbnb_founded) & (df['last_review'] <= today)]
print(f"Rows remaining: {len(df)}")

Valid data range: 2008-01-01 to 2025-10-24
--------------------------------------------------
Future dates found: 3
Dates before 2008: 0
--------------------------------------------------
Rows remaining: 52119

**5. FINAL SUMMARY**

In [15]:
print("\nOUTLIER REMOVAL SUMMARY")
print("-"*30)

print('\nAFTER CLEANING: ')
print(f" -> Total rows: {len(df)}")
print(f" -> Rows removed: {86706 - len(df)}")
print(f" -> Percentage removed: {((86706 - len(df)) / 86706 * 100):.2f} %")

print("\nCLEANED DATA RANGES: ")
print(f" -> minimum_nights: {df['minimum_nights'].min():.0f} to {df['minimum_nights'].max():.0f}")
print(f" -> availability_365: {df['availability_365'].min():.0f} to {df['availability_365'].max():.0f}")
print(f" -> price: ${df['price'].min():.2f} to ${df['price'].max():.2f}")
print(f" -> reviews_per_month: {df['reviews_per_month'].min():.2f} to {df['reviews_per_month'].max():.2f}")
print(f" -> last_review: {df['last_review'].min()} to {df['last_review'].max()}")

OUTLIER REMOVAL SUMMARY
------------------------------

AFTER CLEANING:
 -> Total rows: 52119
 -> Rows removed: 34587
 -> Percentage removed: 39.89 %

CLEANED DATA RANGES:
 -> minimum_nights: 1 to 365
 -> availability_365: 0 to 3677
 -> price: $50.00 to $1200.00
 -> reviews_per_month: 0.00 to 25.23
 -> last_review: 2012-08-25 00:00:00 to 2025-06-26 00:00:00

In [16]:
df = df.drop_duplicates()

In [17]:
len(df)

50304

In [20]:
output_path = '/Users/starboy/Documents/Projects/Airbnb/cleaned_data_after_outlier_removal.csv'
df.to_csv(output_path, index=False)